name: CI-Build
on:
  release:
    types:
      - created

jobs:
  build:
    name: Build Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Get Module Version
        id: module-version
        run: |
          MODULE_VERSION=$(cat module.gradle | grep "moduleVersion =" | awk -F'"' '{print $2}')
          echo "version=$MODULE_VERSION" >> "$GITHUB_OUTPUT"
      - name: Test Build
        run: |
          chmod +x ./gradlew
          ./gradlew :module:assembleRelease
          mv ./out/magisk_module_zygisk_release ./out/ZygiskFrida-${{ steps.module-version.outputs.version }}-release
          mv ./out/magisk_module_riru_release ./out/ZygiskFrida-${{ steps.module-version.outputs.version }}-riru-release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            ${{ github.workspace }}/out/ZygiskFrida-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}